### ISSUE TITLE
FRLTZ is almost impossible to hit

### ISSUE THREAD

**Issue by robertmassaioli** [jthlim/jeff-modifiers#1]
I'm using the Magnet App for Mac and a common keyboard shortcut is to have control and alt hit at the same time. However, trying to hit F for Control and B for Alt turns out to be really hard for me to stroke. Is there a way that this system could be updated to support hitting those two command keys at the same time? Cheers.

**Comment by jthlim** [comment]
FRLTZ should be pretty easy to hit...... The text seems to imply FBLTZ  - and it definitely is harder to stroke than FR-

However, this system isn't going to change just for a few combination that are harder to press - you can fork it and adjust to your preference some alternative, or you can remap magnet to something easier to press.
